server:
  port: 8081

spring:
  application:
    name: ms-usuarios
  profiles:
    active: local       # al arrancar sin argumentos, usa application-local.yml  - test ,prod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

storage:
  service:
    url: lb://ms-storage

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: dGhpcyBpcyBhIHZlcnkgbG9uZyBhbmQgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dA==
  expiration: 86400000