# ========== IDENTIDAD Y PUERTO ==========
server:
  port: 8081

spring:
  application:
    name: ms-usuarios

  # ========== BASE DE DATOS ==========
  datasource:
    url: jdbc:oracle:thin:@xxxxx_high?TNS_ADMIN=C:/{user.dir}/src/main/resources/{nombre_wallet} #aca colocar la direccion de la wallet de la base de datos dejarlo en la carpeta resources de este microservicio
    username: ADMIN
    password: Rodriguez123.
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# ========== EUREKA ==========
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# ========== SWAGGER ==========
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
# ========== SEGURIDAD JWT (opcional, si ya lo tienes implementado) ==========
# se puede generar asi una clave aleatoria openssl rand -base64 32 --esta clave JWT SECRET ,no se sube a github es personal
jwt:
  secret: dGhpcyBpcyBhIHZlcnkgbG9uZyBhbmQgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dA==
  expiration: 86400000