# ========== IDENTIDAD Y PUERTO ==========
server:
  port: 8081

spring:
  application:
    name: ms-usuarios

  # ========== BASE DE DATOS ==========
  datasource:
    url: jdbc:oracle:thin:@frikitienda_high?TNS_ADMIN=C:/Users/visio/Downloads/Wallet_FrikiTienda #<-- Cambiar esta ruta por la ruta donde se encuentra la Wallet que se descargo
    #YAML reconoce mejor el uso de "/" que el uso de "\" para las rutas en Windows
    username: ADMIN
    password: Contrasena123
    driver-class-name: oracle.jdbc.OracleDriver
  # ========== JPA ==========
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# ========== EUREKA ==========
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# ========== SWAGGER ==========
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html #<-- localhost:8081/swagger-ui.html para acceder a la documentación de la API