# ==========  el entorno para pruebas .
#Se activa este perfil para probar los testing.No se usa los otros aplication-test ==========

#Recomendable es usar una base de datos diferente a la de desarrollo o producción,

